behaviors:
  TouchCube:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 50000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 1
      save_replay_buffer: false
      init_entcoef: 1.0
      learning_rate: 0.0003
      learning_rate_schedule: constant
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory:
        memory_size: 128
        sequence_length: 64
    max_steps: 1.25e5
    time_horizon: 64
    summary_freq: 5000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.95
